### ISSUE TITLE
Stack overflow in `RedisResult[List[(K, V)]]`

### ISSUE THREAD

**Issue by buntec** [davenverse/rediculous#104]
Looks like https://github.com/davenverse/rediculous/blob/main/core/shared/src/main/scala/io/chrisdavenport/rediculous/RedisResult.scala#L125-L144 isn't stack safe and can fail for large lists (this happened to me).

**Comment by armanbilge** [comment]
Yeah, here's the recursive call to `pairs` in a non-tail position.

https://github.com/davenverse/rediculous/blob/0d0c2d6df1e6798e1e04d76bb0d246fb80f7dea5/core/shared/src/main/scala/io/chrisdavenport/rediculous/RedisResult.scala#L134-L135

Since this is `Either` this may have to be rewritten with `tailRecM` from Cats 🤔 

Or on second thought, if `tailRecM` is possible it should be possible to just manually write a tail recursive function.

**Comment by buntec** [comment]
I think I have something working in terms of `tailRecM`: https://github.com/buntec/rediculous/blob/fix/pub-sub/core/shared/src/main/scala/io/chrisdavenport/rediculous/RedisResult.scala#L129-L140
